/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    posts: Post;
    media: Media;
    'docs-groups': DocsGroup;
    'docs-sets': DocsSet;
    'docs-access': DocsAccess;
    'payload-markdown-docs-assets': PayloadMarkdownDocsAsset;
    docs: Doc;
    'docs-sync-runs': DocsSyncRun;
    'docs-sync-nonces': DocsSyncNonce;
    'payload-kv': PayloadKv;
    users: User;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    posts: PostsSelect<false> | PostsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'docs-groups': DocsGroupsSelect<false> | DocsGroupsSelect<true>;
    'docs-sets': DocsSetsSelect<false> | DocsSetsSelect<true>;
    'docs-access': DocsAccessSelect<false> | DocsAccessSelect<true>;
    'payload-markdown-docs-assets': PayloadMarkdownDocsAssetsSelect<false> | PayloadMarkdownDocsAssetsSelect<true>;
    docs: DocsSelect<false> | DocsSelect<true>;
    'docs-sync-runs': DocsSyncRunsSelect<false> | DocsSyncRunsSelect<true>;
    'docs-sync-nonces': DocsSyncNoncesSelect<false> | DocsSyncNoncesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    header: Header;
  };
  globalsSelect: {
    header: HeaderSelect<false> | HeaderSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "docs-groups".
 */
export interface DocsGroup {
  id: number;
  title: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  parent?: (number | null) | DocsGroup;
  description?: string | null;
  navTitle?: string | null;
  order?: number | null;
  /**
   * auto generates a docs group landing page. custom lets the site own this group route.
   */
  pageMode?: ('auto' | 'custom') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "docs-sets".
 */
export interface DocsSet {
  id: number;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  group?: (number | null) | DocsGroup;
  /**
   * docs-root serves docs at the docs set route. product-nested serves docs under /docs so the parent route can be used as a product page.
   */
  routeMode?: ('docs-root' | 'product-nested') | null;
  /**
   * Git branch allowed to publish this docs set. The full Git ref is handled internally.
   */
  branch?: string | null;
  /**
   * Allow GitHub pull request events to dry-run or publish this docs set.
   */
  allowPullRequests?: boolean | null;
  publishedAt?: string | null;
  title: string;
  description?: string | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  /**
   * Optional workflow lock-down. Leave disabled to allow any workflow from a trusted GitHub owner/repository and branch.
   */
  advancedSecurity?: {
    /**
     * When enabled, only the workflow refs listed below can publish this docs set.
     */
    enabled?: boolean | null;
    /**
     * Exact GitHub workflow refs, for example owner/repo/.github/workflows/publish-docs.yml@refs/heads/main.
     */
    allowedWorkflowRefs?:
      | {
          value: string;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Latest successful docs set sync status.
   */
  sync?: {
    lastSyncedAt?: string | null;
    lastStatus?: ('failed' | 'pending' | 'success') | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "docs-access".
 */
export interface DocsAccess {
  id: number;
  title: string;
  accessType: 'ed25519' | 'githubOidc';
  identityKey?: string | null;
  /**
   * Identifier sent by signed docs sync requests. Keep this stable for each publishing environment.
   */
  keyId?: string | null;
  /**
   * Ed25519 public key allowed to publish docs. Private keys never belong in Payload.
   */
  publicKey?: string | null;
  /**
   * GitHub owner or organization trusted to publish docs through OIDC.
   */
  owner?: string | null;
  /**
   * Leave off to trust every repository owned by this GitHub owner. Enable to list specific repositories.
   */
  limitRepos?: boolean | null;
  /**
   * Repository names or owner/repository pairs allowed when repo limiting is enabled.
   */
  repositories?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-markdown-docs-assets".
 */
export interface PayloadMarkdownDocsAsset {
  id: number;
  sourceId: string;
  docsSet?: (number | null) | DocsSet;
  kind: 'llms' | 'llms-full' | 'skill' | 'static';
  sourcePath: string;
  route?: string | null;
  contentType: string;
  content: string;
  sourceHash?: string | null;
  sync?: {
    sourceId?: string | null;
    sourcePath?: string | null;
    sourceHashAtLastSync?: string | null;
    contentHashAtLastSync?: string | null;
    lastSyncedAt?: string | null;
    lastSyncRunId?: (number | null) | DocsSyncRun;
    managedBy?: string | null;
    archived?: boolean | null;
    archivedAt?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "docs-sync-runs".
 */
export interface DocsSyncRun {
  id: number;
  sourceId: string;
  repository?: string | null;
  branch?: string | null;
  commit?: string | null;
  actor?: string | null;
  keyId?: string | null;
  mode: 'dry-run' | 'sync';
  status: 'pending' | 'success' | 'failed';
  publishRequested?: boolean | null;
  deleteBehavior?: ('archive' | 'delete' | 'draft' | 'ignore') | null;
  bodyHash?: string | null;
  fileCount?: number | null;
  totalBytes?: number | null;
  summary?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  warnings?:
    | {
        message?: string | null;
        id?: string | null;
      }[]
    | null;
  errors?:
    | {
        message?: string | null;
        id?: string | null;
      }[]
    | null;
  startedAt: string;
  completedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "docs".
 */
export interface Doc {
  id: number;
  title: string;
  navTitle?: string | null;
  description?: string | null;
  /**
   * Optional fully qualified package names used to link related docs sets in generated AI discovery files.
   */
  dependencies?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  publishedAt?: string | null;
  route: string;
  sourcePath: string;
  docsSet?: (number | null) | DocsSet;
  sourceHash?: string | null;
  depth?: number | null;
  order?: number | null;
  parent?: (number | null) | Doc;
  /**
   * Optional hero image rendered above generated docs content.
   */
  heroImage?: (number | null) | Media;
  content?: string | null;
  overrides?: {
    navTitle?: string | null;
    hideFromNav?: boolean | null;
  };
  sync?: {
    sourceId?: string | null;
    sourcePath?: string | null;
    sourceHashAtLastSync?: string | null;
    contentHashAtLastSync?: string | null;
    lastSyncedAt?: string | null;
    lastSyncRunId?: (number | null) | DocsSyncRun;
    managedBy?: string | null;
    archived?: boolean | null;
    archivedAt?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "docs-sync-nonces".
 */
export interface DocsSyncNonce {
  id: number;
  keyId: string;
  nonce: string;
  sourceId?: string | null;
  bodyHash?: string | null;
  syncRunId?: (number | null) | DocsSyncRun;
  expiresAt: string;
  usedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'docs-groups';
        value: number | DocsGroup;
      } | null)
    | ({
        relationTo: 'docs-sets';
        value: number | DocsSet;
      } | null)
    | ({
        relationTo: 'docs-access';
        value: number | DocsAccess;
      } | null)
    | ({
        relationTo: 'payload-markdown-docs-assets';
        value: number | PayloadMarkdownDocsAsset;
      } | null)
    | ({
        relationTo: 'docs';
        value: number | Doc;
      } | null)
    | ({
        relationTo: 'docs-sync-runs';
        value: number | DocsSyncRun;
      } | null)
    | ({
        relationTo: 'docs-sync-nonces';
        value: number | DocsSyncNonce;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "docs-groups_select".
 */
export interface DocsGroupsSelect<T extends boolean = true> {
  title?: T;
  generateSlug?: T;
  slug?: T;
  parent?: T;
  description?: T;
  navTitle?: T;
  order?: T;
  pageMode?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "docs-sets_select".
 */
export interface DocsSetsSelect<T extends boolean = true> {
  generateSlug?: T;
  slug?: T;
  group?: T;
  routeMode?: T;
  branch?: T;
  allowPullRequests?: T;
  publishedAt?: T;
  title?: T;
  description?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  advancedSecurity?:
    | T
    | {
        enabled?: T;
        allowedWorkflowRefs?:
          | T
          | {
              value?: T;
              id?: T;
            };
      };
  sync?:
    | T
    | {
        lastSyncedAt?: T;
        lastStatus?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "docs-access_select".
 */
export interface DocsAccessSelect<T extends boolean = true> {
  title?: T;
  accessType?: T;
  identityKey?: T;
  keyId?: T;
  publicKey?: T;
  owner?: T;
  limitRepos?: T;
  repositories?:
    | T
    | {
        value?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-markdown-docs-assets_select".
 */
export interface PayloadMarkdownDocsAssetsSelect<T extends boolean = true> {
  sourceId?: T;
  docsSet?: T;
  kind?: T;
  sourcePath?: T;
  route?: T;
  contentType?: T;
  content?: T;
  sourceHash?: T;
  sync?:
    | T
    | {
        sourceId?: T;
        sourcePath?: T;
        sourceHashAtLastSync?: T;
        contentHashAtLastSync?: T;
        lastSyncedAt?: T;
        lastSyncRunId?: T;
        managedBy?: T;
        archived?: T;
        archivedAt?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "docs_select".
 */
export interface DocsSelect<T extends boolean = true> {
  title?: T;
  navTitle?: T;
  description?: T;
  dependencies?: T;
  publishedAt?: T;
  route?: T;
  sourcePath?: T;
  docsSet?: T;
  sourceHash?: T;
  depth?: T;
  order?: T;
  parent?: T;
  heroImage?: T;
  content?: T;
  overrides?:
    | T
    | {
        navTitle?: T;
        hideFromNav?: T;
      };
  sync?:
    | T
    | {
        sourceId?: T;
        sourcePath?: T;
        sourceHashAtLastSync?: T;
        contentHashAtLastSync?: T;
        lastSyncedAt?: T;
        lastSyncRunId?: T;
        managedBy?: T;
        archived?: T;
        archivedAt?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "docs-sync-runs_select".
 */
export interface DocsSyncRunsSelect<T extends boolean = true> {
  sourceId?: T;
  repository?: T;
  branch?: T;
  commit?: T;
  actor?: T;
  keyId?: T;
  mode?: T;
  status?: T;
  publishRequested?: T;
  deleteBehavior?: T;
  bodyHash?: T;
  fileCount?: T;
  totalBytes?: T;
  summary?: T;
  warnings?:
    | T
    | {
        message?: T;
        id?: T;
      };
  errors?:
    | T
    | {
        message?: T;
        id?: T;
      };
  startedAt?: T;
  completedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "docs-sync-nonces_select".
 */
export interface DocsSyncNoncesSelect<T extends boolean = true> {
  keyId?: T;
  nonce?: T;
  sourceId?: T;
  bodyHash?: T;
  syncRunId?: T;
  expiresAt?: T;
  usedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: number;
  navItems?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'docs-groups';
                value: number | DocsGroup;
              } | null)
            | ({
                relationTo: 'docs-sets';
                value: number | DocsSet;
              } | null);
          url?: string | null;
          label: string;
        };
        subItems?:
          | {
              link: {
                type?: ('reference' | 'custom') | null;
                newTab?: boolean | null;
                reference?:
                  | ({
                      relationTo: 'docs-groups';
                      value: number | DocsGroup;
                    } | null)
                  | ({
                      relationTo: 'docs-sets';
                      value: number | DocsSet;
                    } | null);
                url?: string | null;
                label: string;
              };
              /**
               * Populate child items from the linked docs group's child groups and docs sets.
               */
              populateChildren?: boolean | null;
              childItems?:
                | {
                    link: {
                      type?: ('reference' | 'custom') | null;
                      newTab?: boolean | null;
                      reference?:
                        | ({
                            relationTo: 'docs-groups';
                            value: number | DocsGroup;
                          } | null)
                        | ({
                            relationTo: 'docs-sets';
                            value: number | DocsSet;
                          } | null);
                      url?: string | null;
                      label: string;
                    };
                    id?: string | null;
                  }[]
                | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  navItems?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
        subItems?:
          | T
          | {
              link?:
                | T
                | {
                    type?: T;
                    newTab?: T;
                    reference?: T;
                    url?: T;
                    label?: T;
                  };
              populateChildren?: T;
              childItems?:
                | T
                | {
                    link?:
                      | T
                      | {
                          type?: T;
                          newTab?: T;
                          reference?: T;
                          url?: T;
                          label?: T;
                        };
                    id?: T;
                  };
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}