export { payloadMarkdownDocs } from './plugin.js'
export type {
  DocsBlockInstallSelection,
  DocsCollectionInstallConfig,
  DocsHeroInstallConfig,
  DocsHeroInstallSelection,
  DocsMarketingBlockKey,
  PayloadMarkdownDocsAccessConfig,
  PayloadMarkdownDocsAuthConfig,
  PayloadMarkdownDocsCollectionConfig,
  PayloadMarkdownDocsCollectionsConfig,
  PayloadMarkdownDocsConfig,
  PayloadMarkdownDocsEndpointConfig,
  PayloadMarkdownDocsPagesConfig,
  PayloadMarkdownDocsPagesRoutingConfig,
  PayloadMarkdownDocsRoutingConfig,
  PayloadMarkdownDocsSyncConfig,
  PayloadMarkdownDocsSyncRevalidateConfig,
  PayloadMarkdownDocsTargetConfig,
} from './types.js'
